#ifndef __RTE_CONFIG_H
#define __RTE_CONFIG_H
#define RTE_EXEC_ENV "linuxapp"
#define RTE_EXEC_ENV_LINUXAPP 1
#define RTE_MACHINE "native"
#define RTE_ARCH "x86_64"
#define RTE_ARCH_X86_64 1
#define RTE_TOOLCHAIN "gcc"
#define RTE_TOOLCHAIN_GCC 1
#undef RTE_FORCE_INTRINSICS
#undef RTE_BUILD_SHARED_LIB
#undef RTE_BUILD_COMBINE_LIBS
#define RTE_LIBNAME "intel_dpdk"
#undef RTE_LIBC
#undef RTE_LIBC_NEWLIB_SRC
#undef RTE_LIBC_NEWLIB_BIN
#undef RTE_LIBC_NETINCS
#undef RTE_LIBGLOSS
#define RTE_LIBRTE_EAL 1
#define RTE_MAX_LCORE 64
#define RTE_MAX_NUMA_NODES 8
#define RTE_MAX_MEMSEG 256
#define RTE_MAX_MEMZONE 2560
#define RTE_MAX_TAILQ 32
#define RTE_LOG_LEVEL 8
#define RTE_LOG_HISTORY 256
#undef RTE_LIBEAL_USE_HPET
#undef RTE_EAL_ALLOW_INV_SOCKET_ID
#undef RTE_EAL_ALWAYS_PANIC_ON_ERROR
#define RTE_LIBRTE_EAL_LINUXAPP 1
#undef RTE_LIBRTE_EAL_BAREMETAL
#define RTE_LIBRTE_EAL_VMWARE_TSC_MAP_SUPPORT 1
#define RTE_LIBRTE_KVARGS 1
#define RTE_LIBRTE_ETHER 1
#undef RTE_LIBRTE_ETHDEV_DEBUG
#define RTE_MAX_ETHPORTS 32
#undef RTE_LIBRTE_IEEE1588
#define RTE_ETHDEV_QUEUE_STAT_CNTRS 16
#define RTE_LIBRTE_EM_PMD 1
#define RTE_LIBRTE_IGB_PMD 1
#undef RTE_LIBRTE_E1000_DEBUG_INIT
#undef RTE_LIBRTE_E1000_DEBUG_RX
#undef RTE_LIBRTE_E1000_DEBUG_TX
#undef RTE_LIBRTE_E1000_DEBUG_TX_FREE
#undef RTE_LIBRTE_E1000_DEBUG_DRIVER
#undef RTE_LIBRTE_E1000_PF_DISABLE_STRIP_CRC
#define RTE_LIBRTE_IXGBE_PMD 1
#undef RTE_LIBRTE_IXGBE_DEBUG_INIT
#undef RTE_LIBRTE_IXGBE_DEBUG_RX
#undef RTE_LIBRTE_IXGBE_DEBUG_TX
#undef RTE_LIBRTE_IXGBE_DEBUG_TX_FREE
#undef RTE_LIBRTE_IXGBE_DEBUG_DRIVER
#undef RTE_LIBRTE_IXGBE_PF_DISABLE_STRIP_CRC
#define RTE_LIBRTE_IXGBE_RX_ALLOW_BULK_ALLOC 1
#undef RTE_LIBRTE_IXGBE_ALLOW_UNSUPPORTED_SFP
#define RTE_LIBRTE_VIRTIO_PMD 1
#undef RTE_LIBRTE_VIRTIO_DEBUG_INIT
#undef RTE_LIBRTE_VIRTIO_DEBUG_RX
#undef RTE_LIBRTE_VIRTIO_DEBUG_TX
#undef RTE_LIBRTE_VIRTIO_DEBUG_DRIVER
#undef RTE_LIBRTE_VIRTIO_DEBUG_DUMP
#define RTE_LIBRTE_VMXNET3_PMD 1
#undef RTE_LIBRTE_VMXNET3_DEBUG_INIT
#undef RTE_LIBRTE_VMXNET3_DEBUG_RX
#undef RTE_LIBRTE_VMXNET3_DEBUG_TX
#undef RTE_LIBRTE_VMXNET3_DEBUG_TX_FREE
#undef RTE_LIBRTE_VMXNET3_DEBUG_DRIVER
#define RTE_LIBRTE_PMD_RING 1
#define RTE_PMD_RING_MAX_RX_RINGS 16
#define RTE_PMD_RING_MAX_TX_RINGS 16
#undef RTE_LIBRTE_PMD_PCAP
#undef RTE_LIBRTE_PMD_XENVIRT
#define RTE_PMD_PACKET_PREFETCH 1
#define RTE_LIBRTE_RING 1
#undef RTE_LIBRTE_RING_DEBUG
#undef RTE_RING_SPLIT_PROD_CONS
#define RTE_LIBRTE_MEMPOOL 1
#define RTE_MEMPOOL_CACHE_MAX_SIZE 512
#undef RTE_LIBRTE_MEMPOOL_DEBUG
#define RTE_LIBRTE_MBUF 1
#undef RTE_LIBRTE_MBUF_DEBUG
#define RTE_MBUF_SCATTER_GATHER 1
#define RTE_MBUF_REFCNT_ATOMIC 1
#define RTE_PKTMBUF_HEADROOM 128
#define RTE_LIBRTE_TIMER 1
#undef RTE_LIBRTE_TIMER_DEBUG
#define RTE_LIBRTE_MALLOC 1
#undef RTE_LIBRTE_MALLOC_DEBUG
#define RTE_MALLOC_MEMZONE_SIZE 11M
#define RTE_LIBRTE_CMDLINE 1
#undef RTE_LIBRTE_CMDLINE_DEBUG
#define RTE_LIBRTE_HASH 1
#undef RTE_LIBRTE_HASH_DEBUG
#define RTE_LIBRTE_LPM 1
#undef RTE_LIBRTE_LPM_DEBUG
#define RTE_LIBRTE_POWER 1
#undef RTE_LIBRTE_POWER_DEBUG
#define RTE_MAX_LCORE_FREQS 64
#define RTE_LIBRTE_NET 1
#define RTE_LIBRTE_METER 1
#define RTE_LIBRTE_SCHED 1
#undef RTE_SCHED_RED
#undef RTE_SCHED_COLLECT_STATS
#undef RTE_SCHED_SUBPORT_TC_OV
#define RTE_SCHED_PORT_N_GRINDERS 8
#define RTE_LIBRTE_KNI 1
#undef RTE_KNI_KO_DEBUG
#undef RTE_KNI_VHOST
#define RTE_KNI_VHOST_MAX_CACHE_SIZE 1024
#undef RTE_KNI_VHOST_VNET_HDR_EN
#undef RTE_KNI_VHOST_DEBUG_RX
#undef RTE_KNI_VHOST_DEBUG_TX
#undef RTE_LIBRTE_XEN_DOM0
#undef RTE_INSECURE_FUNCTION_WARNING
#define RTE_APP_TEST 1
#define RTE_TEST_PMD 1
#undef RTE_TEST_PMD_RECORD_CORE_CYCLES
#undef RTE_TEST_PMD_RECORD_BURST_STATS
#undef RTE_NIC_BYPASS
#endif /* __RTE_CONFIG_H */
